### PR TITLE
Update with Endwalker action detection.

### PR DESCRIPTION
**Pull request by sigonasr2**
Quick fix for EW actions. Combat Skill IDs go up into the high 26000's

### CODE REVIEW

**Comment by reyronald** [comment]
I just figured this out too. Don't know exactly what the upper limit should be but 2000 is definitely too low now after EW was released.

Can we get this looked at @Rawrington ?

**Comment by KFung95** [comment]
The combat skill IDs go up to 29500. I verified it locally and have a working version.

**Comment by sigonasr2** [comment]
Glad I was generous with the upper limit I chose then. Thanks for clarifying. Hopefully this gets pushed up soon.

**Comment by Rawrington** [comment]
Hi! Sorry about the wait! I've been "enjoying" the raid tier and forgot to merge this in, I'll get on it now!

**Comment by Rawrington** [comment]
Just updated my github pages deployment, give it a test for me (when the cache updates) to be sure!

**Comment by reyronald** [comment]
@Rawrington All new Scholar and Paladin actions are showing up now ! Thanks @sigonasr2  :)

image

image

@Rawrington  While I have your attention, an off-topic question we can take elsewhere if necessary: would it be possible to also display item usage in the timeline ? So that potions also show up in the rotation. Right now they don't

**Pull request merged**
